login:
    pattern: ^/login$
profiler:
    pattern: ^/_profiler/
secured:
    pattern: ^/admin/
    form:
        login_path: /login
        check_path: /login_check
        default_target_path: dashboard
        always_use_default_target_path: true
    logout:
        logout_path: /logout
    users:
        aaron:
            - [ROLE_ADMIN]
            - BFEQkknI/c+Nd7BaG7AaiyTfUFby/pkMHy3UsYqKqDcmvHoPRX/ame9TnVuOV2GrBH0JK9g4koW+CgTYI9mK+w==